#!/usr/bin/env bash
# First-time single-server deployment of the project-risk-system (INTERNAL_MVP).
#
# This orchestrates the validated T035 compose stack: it does NOT invent a
# second deployment architecture. It only sequences the approved commands:
# validate config -> build images -> start postgres/redis -> wait health ->
# alembic upgrade head -> (optional) risk-platform-seed -> up stack -> health.
#
# Usage:
#   ./infra/deploy/deploy.sh            # deploy without seeding
#   ./infra/deploy/deploy.sh --seed     # first-time deploy + initial admin seed
#   ./infra/deploy/deploy.sh --help
#
# Secrets are never generated here. The operator must first run
# `bash infra/scripts/init-secrets.sh` and fill .env.production.
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
. "${SCRIPT_DIR}/lib/common.sh"
deploy_root_init
deploy_conf_load

SEED=0
usage() {
  cat <<'EOF'
Usage: deploy.sh [--seed] [--help]

  --seed     Run `risk-platform-seed` after migration (first-time init only).
             Seed is idempotent but never re-runs by default; pass this only
             for the initial bootstrap or to reconcile reference data.
  --help     Show this help.

Prerequisites (operator, run once before first deploy):
  1. cp infra/env.example .env.production   # then fill real values
  2. bash infra/scripts/init-secrets.sh     # session key + TLS cert
  3. Provide a backup KEK (for later backup.sh; not required to boot)

Required env in .env.production: POSTGRES_PASSWORD, DATA_ENCRYPTION_KEY,
CORS_ORIGIN, INITIAL_ADMIN_PASSWORD (only used when --seed).
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --seed) SEED=1; shift ;;
    --help|-h) usage; exit 0 ;;
    *) die "unknown argument: $1 (try --help)" ;;
  esac
done

cd "${PROJECT_ROOT}"

log "single-server deployment (INTERNAL_MVP)"
log "project root: ${PROJECT_ROOT}"
log "compose file: $(compose_file_path)"
log "env file:     ${ENV_FILE}"

# --- prerequisites -----------------------------------------------------------
require_cmd docker "Docker Engine"
require_cmd git
docker compose version >/dev/null 2>&1 \
  || die "docker compose v2 plugin not found (run 'docker compose version')"
require_project_root
require_env_file

# Secret / cert files that the compose stack mounts. session key + TLS cert are
# generated by infra/scripts/init-secrets.sh; TLS may be replaced by a CA-issued
# cert before real deployment.
SESSION_KEY="${PROJECT_ROOT}/infra/secrets/project_risk_session_key"
TLS_CRT="${PROJECT_ROOT}/infra/proxy/certs/tls.crt"
TLS_KEY="${PROJECT_ROOT}/infra/proxy/certs/tls.key"
[[ -f "${SESSION_KEY}" ]] \
  || die "session key missing: ${SESSION_KEY} (run 'bash infra/scripts/init-secrets.sh')"
[[ -f "${TLS_CRT}" && -f "${TLS_KEY}" ]] \
  || die "TLS cert/key missing: ${TLS_CRT}, ${TLS_KEY} (run 'bash infra/scripts/init-secrets.sh' or place CA-issued cert)"

# --- 1. config pre-validation -----------------------------------------------
log "validating compose config"
compose config --quiet || die "docker compose config failed (check ${ENV_FILE})"

# --- 2. build production images ---------------------------------------------
log "building production images (api + web)"
compose build --pull api web || die "image build failed"

# --- 3. start durable layer first -------------------------------------------
log "starting postgres + redis"
compose up -d --no-deps postgres redis || die "failed to start postgres/redis"

wait_until "postgres healthy" \
  compose exec -T postgres pg_isready -U "${POSTGRES_USER:-project_risk}" -d "${POSTGRES_DB:-project_risk}"
wait_until "redis healthy" \
  compose exec -T redis redis-cli ping

# --- 4. database migration ---------------------------------------------------
log "applying alembic migrations (upgrade head)"
compose exec -T api alembic upgrade head \
  || die "alembic upgrade head failed (see 'logs.sh api')"

# --- 5. optional first-time seed --------------------------------------------
if (( SEED )); then
  log "running risk-platform-seed (first-time bootstrap)"
  # Seed reads INITIAL_ADMIN_* from the api container env (already injected via
  # the compose env file). It never prints the password and never overwrites an
  # existing administrator's password.
  compose exec -T api risk-platform-seed \
    || die "risk-platform-seed failed (credentials are validated by the seed itself; see 'logs.sh api')"
  ok "seed completed (initial administrator created with mustChangePassword=true)"
else
  log "skipping seed (pass --seed for first-time admin bootstrap)"
fi

# --- 6. start the full stack -------------------------------------------------
log "starting full stack (api, worker, scheduler, web, proxy)"
compose up -d || die "failed to start the stack"

# --- 7. unified healthcheck --------------------------------------------------
log "running unified healthcheck"
if "${SCRIPT_DIR}/healthcheck.sh"; then
  printf '\n'
  ok "deployment complete"
  git rev-parse HEAD > "${PROJECT_ROOT}/infra/deploy/.deployed-sha"
  log "recorded deployed SHA: $(git rev-parse HEAD)"
  log "access: ${PUBLIC_BASE_URL}"
else
  die "stack started but healthcheck FAILED — run 'infra/deploy/status.sh' and 'infra/deploy/logs.sh'"
fi
